name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  change-detect:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: read
    outputs:
      duplicate_check: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'always'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule", "merge_group"]'

  build:
    needs: change-detect
    if: needs.change-detect.outputs.duplicate_check != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.0

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Lint
        run: |
          npm run lint

      - name: Test/Coverage
        run: |
          npm run coverage

      - name: Download main baseline coverage artifact
        if: ${{ github.event_name == 'pull_request' }}
        uses: dawidd6/action-download-artifact@v8
        with:
          branch: main
          event: push
          workflow_conclusion: success
          name: carry-tracker-coverage
          path: coverage-main

      - name: Upload coverage artifact
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: carry-tracker-coverage
          path: ./coverage/**

      - name: Generate coverage report
        if: ${{ hashFiles('coverage/coverage-summary.json') != '' }}
        uses: davelosert/vitest-coverage-report-action@v2.9.3
        with:
          threshold-icons: "{0: '🔴', 70: '🟠', 85: '🟢'}"
          json-summary-compare-path: ${{ github.event_name == 'pull_request' && './coverage-main/coverage-summary.json' || '' }}
